image : wtakase/geant4:10.1-centos7
  
before_script:
  - uname -a
  - echo $CC $CXX 
  - cmake --version
  - whereis boost 
  - curl -o /opt/boost_1_54_0.tar.gz https://sourceforge.net/projects/boost/files/boost/1.54.0/boost_1_54_0.tar.gz
  - cd /opt/
  - tar xf boost_1_54_0.tar.gz
  - rm /opt/boost_1_54_0.tar.gz
  - cd /opt/root
  - source bin/thisroot.sh
  - cd -
  - cd /opt/geant4/bin
  - source ./geant4.sh
  - cd -

build:
  script:
    - mkdir build/
    - cd build
    - cmake -DBOOST_ROOT=/opt/boost_1_54_0 ..
    - make
